name: Docker Upload Main Branch
run-name: ${{ github.actor }} is building and deploying to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  docker:
    environment: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ env.COMMIT_SHORT_SHA }}
